### ISSUE TITLE
Clarify use of --reference

### ISSUE THREAD

**Issue by pixelsoccupied** [openshift/kube-compare#15]
Currently --reference is a path to a `metadata.yaml` and not just a simple annotated `.yaml`. This is should be reflected in helper/api?

**Comment by nocturnalastro** [comment]
`--reference` Seem to be the path to the director where the reference/`metadata.yaml` file is.
Which also means that the metadata.yaml file is required and required to be named as such.

I think if reference were instead the path to the `metadata.yaml` it would be better flexibility wise and would make more sense to the user. You can then still then use the parent dir for the base for any relative paths in the `metadata.yaml`.

**Comment by pixelsoccupied** [comment]
/kind api-change 

Also like we spoke about it earlier...`--reference` should be updated to `--reference-manifest` and the like should `metadata.yaml` to `manifest.yaml`

**Comment by nocturnalastro** [comment]
@lack This is one can you close it?
