### ISSUE TITLE
Linting as a blocker for merge. 

### ISSUE THREAD

**Issue by nocturnalastro** [openshift/kube-compare#22]
Found some cases of errors not being handled or dropped. 
I suggest we add `golangci-lint` or some other linter as a blocker on merges to act as a guard against such things happening.

**Comment by nocturnalastro** [comment]
I made a draft PR addressing the issues raised by running a default config of golangci-lint here: https://github.com/openshift/kube-compare/pull/23

**Comment by nocturnalastro** [comment]
It spotted a [shadowed definition](https://github.com/openshift/kube-compare/pull/23/files#diff-335062749225167ffe134568cee53f7d38835f0b9941ce9aa67efc6d1f26bd91L83) which may have caused issues

**Comment by pixelsoccupied** [comment]
Let's include the `golangci-lint` yml config and call from our CI job! 

/kind feature

**Comment by AlinaSecret** [comment]
@pixelsoccupied  @nocturnalastro  can we close this?

**Comment by nocturnalastro** [comment]
Yes
